/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package quizserver;

import java.io.FileReader;
import java.io.IOException;
import java.util.Scanner;
import javax.swing.*;

/**
 *
 * @author ritesh
 */
public class connection extends javax.swing.JFrame {

    int fcl, lcl;
    int clientid;
    static int n,np,easy,med,hard,time,tf;
    static String ip;
    static int port;
    static ServerHome home;
    static void getconf()throws IOException
    {
        Scanner sc = new Scanner(new FileReader("server.conf"));
        sc.next();
        ip = sc.next();
        sc.next();
        port = sc.nextInt();
        sc.next();
        n = sc.nextInt();
        sc.next();
        np = sc.nextInt();
        sc.next();
        easy = sc.nextInt();
        sc.next();
        med = sc.nextInt();
        sc.next();
        hard = sc.nextInt();
        sc.next();
        time = sc.nextInt();
        sc.next();
        tf = sc.nextInt();
        sc.close();
        
    }
    public connection(int n) throws IOException {
        initComponents();
        this.setVisible(true);
        jList1.setVisible(true);
        nextbutton.setVisible(false);
        //this.getContentPane().setBackground(Color.black);
        DefaultListModel model = new DefaultListModel();   
        jList1.setModel(model);
        connection.getconf();
        model.addElement("Waiting for clients");           
        QuizServer qobj = new QuizServer();
        qobj.initializesocket(port,ip);
        for (int i = 0; i < n; i++) 
        {
        
            String str="Group-";
            String str2 = Integer.toString(i+1);
            str=str+str2;
            str=str+" is connected now";
            clientid = qobj.makeConnection();
            //String str2 = Integer.toString(clientid);
            model.addElement(str);
            jList1.setModel(model);
            if (i == 0) 
            {
                fcl = clientid;
            }
        }
        lcl = clientid;
        model.addElement("All Clients have connected Now"); 
        nextbutton.setVisible(true);
    }

    private connection() {
        //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jLabel1 = new javax.swing.JLabel();
        nextbutton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(23, 11, 11));
        setForeground(new java.awt.Color(29, 10, 10));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jList1.setBackground(new java.awt.Color(156, 156, 156));
        jScrollPane1.setViewportView(jList1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 480, 250));

        jLabel1.setForeground(new java.awt.Color(100, 86, 86));
        jLabel1.setText("No. Of Clients");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, 20));

        nextbutton.setText("Proceed Next");
        nextbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextbuttonActionPerformed(evt);
            }
        });
        getContentPane().add(nextbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 320, -1, -1));

        setSize(new java.awt.Dimension(559, 393));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void nextbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextbuttonActionPerformed
        // TODO add your handling code here:
        home = new ServerHome(fcl, lcl);
        home.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_nextbuttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(connection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(connection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(connection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(connection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new connection().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JList jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton nextbutton;
    // End of variables declaration//GEN-END:variables
}
