/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package quizserver;

import java.io.FileReader;
import java.io.IOException;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author ritesh
 */
public final class QuizRound extends javax.swing.JFrame {
static String[] group;
static int[] score;
//int n,ch;
int fcl,lcl;
String[] str={"hello1","hello2","hello3","hello4","hello5","hello6"};
String[] pstr= new String[2];
String q ;
String[] op= new String[4];
String ans;
String level;
int sq;
int startc;
int[] bvisit = new int[connection.n];
int[] pvisit = new int[connection.n];
int marks;
static int send=0;
int i;
DefaultListModel model = new DefaultListModel();
static DefaultListModel model1 = new DefaultListModel();
DefaultListModel model2 = new DefaultListModel();
public void updateScore()
{
    model.removeAllElements();
    for(int k=fcl;k<=lcl;k++)
    {
        String temp=group[k];
        temp=temp+"    ";
        temp=temp+Integer.toString(score[k]);
        model.addElement(temp);
    }
}
 public QuizRound(int f,int l,int value)
 {
        fcl=startc=f;
        lcl=l;
        group=new String[l+1];
        score=new int[l+1];
        initComponents();
        //jButton3.disable();
        jButton3.setEnabled(false);
        int count=1;
        for(int j=fcl;j<=lcl;j++)
        {  
            String temp="Group-";
            temp=temp+ Integer.toString(count++);
            group[j]=temp;
        }
        jList3.setModel(model);
        jList1.setModel(model1);
        jList2.setModel(model2);
        if(value==1)
            model1.addElement("Buzzer Round");
        else
            model1.addElement("Passing Round");
        updateScore();
 }
    
    
void getquesbuzzer() throws IOException
{
    int n1=connection.n;
    Scanner br = new Scanner(new FileReader("quesbuzzer.txt"));
    do
    n1 = (int)((Math.random()*(n1)));
    while(bvisit[n1]==1);
    n1 = (int)((Math.random()*(n1)));  
    sq=n1;
        System.out.println("before send "+bvisit[sq]);
    for(int i=0;i<n1;i++)
        {
            q = br.nextLine();
            op[0] = br.nextLine();
            op[1] = br.nextLine();
            op[2] = br.nextLine();
            op[3] = br.nextLine();
            ans = br.nextLine();
            //System.out.println("q " +q);

            if(q.charAt(0)=='e'|| q.charAt(0)=='E')
            {
                    level = "easy";
                    marks=connection.easy;
            }
            else if(q.charAt(0)=='h'|| q.charAt(0)=='H')
            {
                    level = "hard";
                    marks=connection.med;
            }
            else 	
            {
                    level = "medium";
                    marks=connection.hard;
            }
            br.nextLine();
        }
    br.close();
}
void getquespassing() throws IOException
{
    int n1=connection.n;
    Scanner br = new Scanner(new FileReader("quespassing.txt"));
    do
    n1 = (int)((Math.random()*(n1)));
    while(pvisit[n1]==1);
    n1 = (int)((Math.random()*(n1)));  
    sq=n1;
        System.out.println("before send "+bvisit[sq]);
    for(int i=0;i<n1;i++)
        {
            q = br.nextLine();
            ans = br.nextLine();
            //System.out.println("q " +q);

            if(q.charAt(0)=='e'|| q.charAt(0)=='E')
            {
                    level = "easy";
                    marks=connection.easy;
            }
            else if(q.charAt(0)=='h'|| q.charAt(0)=='H')
            {
                    level = "hard";
                    marks=connection.med;
            }
            else 	
            {
                    level = "medium";
                    marks=connection.hard;
            }
            br.nextLine();
        }
    br.close();
}    
String getansbuzzer(String c)
{
    for(int i=0;i<4;i++)
            if(op[i].charAt(0)==c.charAt(0))
                return op[i];
    return null;
}
    public QuizRound() {
        initComponents();
        }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList();
        jLabel3 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList3 = new javax.swing.JList();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(16, 6, 6));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Score Board");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 10, -1, 20));

        jButton1.setText("Send");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 450, -1, -1));

        jList1.setModel(new javax.swing.AbstractListModel() {
            String[] strings = new String[20];
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(jList1);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 400, 150));

        jLabel2.setText("Information");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jList2.setModel(new javax.swing.AbstractListModel() {
            String[] strings = new String[20];
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(jList2);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 400, 110));

        jLabel3.setText("Question");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 80, -1));

        jButton5.setText("Reset");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 450, -1, -1));

        jButton6.setText("Get Question");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 370, -1, -1));

        jList3.setModel(new javax.swing.AbstractListModel() {
            String[] strings = new String[100];
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList3);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 40, 190, 300));

        jButton3.setText("Back");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 450, -1, -1));

        jButton4.setText("Send Score");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 370, -1, -1));

        setSize(new java.awt.Dimension(677, 554));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int k;
        ServerHome home=new ServerHome();
        QuizServer obj=new QuizServer();
        if(ServerHome.quesno>0)
        {
            if(ServerHome.value==1)
            {
                    str[0]=q;
                    str[1]=op[0];
                    str[2]=op[1];
                    str[3]=op[2];
                    str[4]=op[3];
                    str[5]="level "+level;
                    obj.broadcastMessage(str,fcl,lcl);
                    String x=obj.buzzerRound(fcl,lcl,connection.time);
                    String[] splited = x.split("\\s+");
                    int len=splited.length;
                    for(int l=0;l<len;l++)
                        System.out.println(splited[l]);
                    //model1.addElement(x);
                    ServerHome.quesno--;
                    bvisit[sq]=1;
                    int now=0;
                    if(!splited[2].equalsIgnoreCase("nil"))
                    {
                       now=Integer.parseInt(splited[1]);
                       String temp1=group[now];
                       temp1=temp1+" Gives the answer";
                       model1.addElement(temp1);
                       if(splited[2].equals(ans))
                       {
                           score[now]=score[now]+marks;
                           String[] msg=new String[1];
                           msg[0]="Ans of the question was option-" +ans+", Given by "+group[now];
                           obj.broadcastMessage(msg, fcl, lcl);
                       }else
                       {
                           score[now]=score[now]-marks;
                           String[] msg=new String[1];
                           msg[0]="Ans of the question was option-" +ans;
                           obj.broadcastMessage(msg, fcl, lcl);
                       }

                    }
                    else
                    {
                    model1.addElement("Timeout: No-one gives the answer");
                    }
                    System.out.println("after send "+bvisit[sq]);
                    model2.removeAllElements();
                    updateScore();
                    if(ServerHome.quesno==0)
                    {
                        JOptionPane.showMessageDialog(null,"No. Of Questions are over",null,JOptionPane.INFORMATION_MESSAGE); 
                        jButton1.setEnabled(false);
                        jButton6.setEnabled(false);
                        jButton3.setEnabled(true);

                    }
            }else
            {               
                int t=connection.time;
		int flag=0;
                pstr[0]=q;
                pstr[1]="level "+level;
		obj.broadcastMessage(pstr,fcl,lcl);
		int currc=startc;
		do
		{
		String x=obj.passRound(fcl,lcl,currc,flag,t);
                pvisit[sq]=1;
		System.out.println("Passing Round\n" + x +"\n");
                if(flag==0)
			flag=1;
                if(x.length()==0)
                {
                    JOptionPane.showMessageDialog(null,"Timeout for "+group[currc],null,JOptionPane.INFORMATION_MESSAGE);
                }else
                {
                    int dialogResult = JOptionPane.showConfirmDialog (null, "Answer From Group-"+(lcl-currc)+" is "+x+"\n Is it correct?","Information",JOptionPane.YES_NO_OPTION);
                    if(dialogResult == JOptionPane.YES_OPTION)
                    {
                        score[currc]=score[currc]+marks;
                        String[] msg=new String[1];
                        msg[0]="Ans of the question was-" +ans+", Given by "+group[currc];
                        obj.broadcastMessage(msg, fcl, lcl);
                        updateScore();
                        break;
                    }else
                        score[currc]=score[currc]-marks;
                }
		if(currc<lcl)
			currc++;
		else
			currc=fcl;
                if(t>5)
                t=t-connection.tf;
                updateScore();
		}while(startc!=currc);
		if(startc<lcl)
			startc++;
		else 
			startc=fcl;
                ServerHome.quesno--;
                JOptionPane.showMessageDialog(null,"Send Next Question",null,JOptionPane.INFORMATION_MESSAGE);
                model2.removeAllElements();
                if(ServerHome.quesno==0)
                {
                    JOptionPane.showMessageDialog(null,"No. Of Questions are over",null,JOptionPane.INFORMATION_MESSAGE); 
                    jButton1.setEnabled(false);
                    jButton6.setEnabled(false);
                    jButton3.setEnabled(true);
                    
                }
            }
        }else
           JOptionPane.showMessageDialog(null,"No. Of Questions are over",null,JOptionPane.INFORMATION_MESSAGE); 
    
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed

        model2.removeAllElements();
        try {   
            if(ServerHome.value==1)
               getquesbuzzer();
            else
               getquespassing(); 
        model2.addElement(q);
        if(ServerHome.value==1)
        {
        model2.addElement(op[0]);
        model2.addElement(op[1]);
        model2.addElement(op[2]);
        model2.addElement(op[3]);
        }
        model2.addElement(ans);
        model2.addElement("marks are "+marks);
    } catch (IOException ex) {
        Logger.getLogger(QuizRound.class.getName()).log(Level.SEVERE, null, ex);
    }
       
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        jButton3.setEnabled(false);
        jButton1.setEnabled(true);
        jButton6.setEnabled(true);
        connection.home.setVisible(true);
        this.setVisible(false);
        jButton3.setEnabled(false);
        
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        String[] points=new String[lcl-fcl+1];
        int i=0,j;
        for(j=fcl;j<=lcl;j++)
        {
            String temp=group[j]+" Marks are:  ";
            temp=temp+Integer.toString(score[j]);
            points[i]=temp;
            i++;             
        }
        QuizServer obj=new QuizServer();
        obj.broadcastMessage(points,fcl,lcl);
        //obj=null;
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuizRound.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuizRound.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuizRound.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuizRound.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>           
            
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QuizRound().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JList jList1;
    private javax.swing.JList jList2;
    private javax.swing.JList jList3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    // End of variables declaration//GEN-END:variables
}
