/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package quizserver;

import java.awt.Color;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import static quizserver.QuizRound.model1;
/**
 *
 * @author ritesh
 */
public class ServerHome extends javax.swing.JFrame {

    /**
     * Creates new form ServerHome
     */
    static int hfcl,hlcl;
    static int value,quesno;
    static int aques,aques2;
    static QuizRound qobj=null;
    public ServerHome(int fcl,int lcl) 
    {
        initComponents();
        //this.getContentPane().setBackground(Color.black);
        hfcl=fcl;
        hlcl=lcl;
        aques=connection.n;
        aques2=connection.np;
        ButtonGroup bg1 = new ButtonGroup( );
        bg1.add(BuzzerRound);
        bg1.add(PassingRound);
        BuzzerRound.setSelected(true);
    }
    public ServerHome()
    {
    }
    /*public ServerHome(int x)
    {
        initComponents();
        ButtonGroup bg1 = new ButtonGroup( );
        bg1.add(BuzzerRound);
        bg1.add(PassingRound);
        BuzzerRound.setSelected(true);
        aques=connection.n-x;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        BuzzerRound = new javax.swing.JRadioButton();
        PassingRound = new javax.swing.JRadioButton();
        textfeild = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, -1, -1));

        BuzzerRound.setText("Buzzer Round");
        BuzzerRound.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuzzerRoundActionPerformed(evt);
            }
        });
        getContentPane().add(BuzzerRound, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        PassingRound.setText("Passing Round");
        getContentPane().add(PassingRound, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        textfeild.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textfeildActionPerformed(evt);
            }
        });
        getContentPane().add(textfeild, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 130, -1));

        jLabel1.setText("No. Of Questitions");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));

        setSize(new java.awt.Dimension(449, 330));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        if(BuzzerRound.isSelected())
            value=1;
        else
            value=2;
        if(textfeild.getText().equals(""))
        {
         JOptionPane.showMessageDialog(null,"Enter No. Of Questions",null,JOptionPane.INFORMATION_MESSAGE);  
        }else
                if(aques<(Integer.parseInt(textfeild.getText())) && value==1)
                {
                   JOptionPane.showMessageDialog(null,"There is only "+aques+" questions are available for Buzzer Round",null,JOptionPane.INFORMATION_MESSAGE); 
                }
                else if(aques2<(Integer.parseInt(textfeild.getText())))
                {
                   JOptionPane.showMessageDialog(null,"There is only "+aques2+" questions are available for Passing Round",null,JOptionPane.INFORMATION_MESSAGE);
                }
         else
        {
            quesno=Integer.parseInt(textfeild.getText());
            if(value==1)
               aques=aques-quesno;
            else
               aques2=aques2-quesno; 
            if(qobj==null)
            qobj=new QuizRound(hfcl,hlcl,value);
            else
            {
                if(value==1)
                    QuizRound.model1.addElement("Buzzer Round");
                else
                    QuizRound.model1.addElement("Passing Round");
                qobj.updateScore();
            }
            qobj.setVisible(true);
            this.setVisible(false);
        }
        textfeild.setText(null);
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void BuzzerRoundActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuzzerRoundActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BuzzerRoundActionPerformed

    private void textfeildActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textfeildActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textfeildActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ServerHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ServerHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ServerHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ServerHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ServerHome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton BuzzerRound;
    private javax.swing.JRadioButton PassingRound;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField textfeild;
    // End of variables declaration//GEN-END:variables
}
